"""The frozen analysis plan, what it compiles to, and what running it produces.

:mod:`behavio.protocol.schema` is the declaration -- cohort, units, estimands, candidates,
split geometry, recovery requirements, reporting bounds -- together with its lifecycle and
amendment rules. It is *the study* in the scientific sense: the thing that was
pre-registered. :class:`~behavio.trials.Study` is that study's trials.

:mod:`behavio.protocol.compiler` turns a frozen protocol and a real dataset into an
execution plan and refuses the ones that cannot be executed as declared.
:mod:`behavio.protocol.runner` executes the plan. :mod:`behavio.protocol.exact_recovery`
runs recovery through the identical compiled plan, so recovery evidence is evidence about
the design that actually ran.
"""

from behavio.protocol.compiler import (
    AuditLevel,
    CohortManifest,
    CompiledFold,
    CompiledInnerFold,
    CompiledProtocol,
    ExecutionPlan,
    IdentityRecord,
    MaterializedProtocol,
    ObservationContractRule,
    ObservationContractViolation,
    ProtocolAudit,
    ProtocolAuditIssue,
    ProtocolCompilationError,
    compile_execution_plan,
    materialize_protocol,
    validate_observation_contract,
)
from behavio.protocol.exact_recovery import (
    ExactRecoveryError,
    ExactRecoveryReport,
    ExactRecoveryRun,
    GateStatus,
    RecoveryCase,
    RecoveryFailure,
    RecoveryGate,
    RecoveryReplicate,
    run_exact_recovery,
)
from behavio.protocol.runner import (
    CalibrationBin,
    CalibrationEstimand,
    CalibrationSummary,
    CandidateRun,
    CandidateVerification,
    DeclarationCheck,
    DeclarationFinding,
    EvaluationReport,
    NestedEvaluationReport,
    NestedFold,
    NestedProtocolRun,
    PointwisePrediction,
    ProtocolRun,
    ProtocolRunError,
    Ranking,
    RankingStatus,
    ScoreSummary,
    UnitScore,
    fold_to_dict,
    run_nested_protocol,
    run_protocol,
    verify_candidate_declarations,
)
from behavio.protocol.schema import (
    PROTOCOL_SCHEMA_VERSION,
    AggregationWeighting,
    CandidateInference,
    CandidateSpec,
    CohortPredicate,
    CohortSpec,
    ComparisonSpec,
    EstimandSpec,
    LifecycleEvent,
    NestedSelectionSpec,
    ObservationDataType,
    ObservationRole,
    ObservationSpec,
    PanelSpec,
    PredicateOperator,
    PredictionInformation,
    ProtocolAmendment,
    ProtocolClockSpec,
    ProtocolLifecycleError,
    ProtocolState,
    ProtocolValidationError,
    RecoveryKind,
    RecoverySpec,
    ReportingSpec,
    ScoreMetric,
    SelectionTieBreak,
    Setting,
    SourceSpec,
    StudyProtocol,
    TransformSpec,
    TransformVisibility,
    UnitRole,
    UnitSpec,
    ValidationGeometry,
    ValidationSpec,
    WinnerPolicy,
    protocol_from_dict,
    protocol_from_json,
)

__all__ = [
    "PROTOCOL_SCHEMA_VERSION",
    "AggregationWeighting",
    "AuditLevel",
    "CalibrationBin",
    "CalibrationEstimand",
    "CalibrationSummary",
    "CandidateInference",
    "CandidateRun",
    "CandidateSpec",
    "CandidateVerification",
    "CohortManifest",
    "CohortPredicate",
    "CohortSpec",
    "ComparisonSpec",
    "CompiledFold",
    "CompiledInnerFold",
    "CompiledProtocol",
    "DeclarationCheck",
    "DeclarationFinding",
    "EstimandSpec",
    "EvaluationReport",
    "ExactRecoveryError",
    "ExactRecoveryReport",
    "ExactRecoveryRun",
    "ExecutionPlan",
    "GateStatus",
    "IdentityRecord",
    "LifecycleEvent",
    "MaterializedProtocol",
    "NestedEvaluationReport",
    "NestedFold",
    "NestedProtocolRun",
    "NestedSelectionSpec",
    "ObservationContractRule",
    "ObservationContractViolation",
    "ObservationDataType",
    "ObservationRole",
    "ObservationSpec",
    "PanelSpec",
    "PointwisePrediction",
    "PredicateOperator",
    "PredictionInformation",
    "ProtocolAmendment",
    "ProtocolAudit",
    "ProtocolAuditIssue",
    "ProtocolClockSpec",
    "ProtocolCompilationError",
    "ProtocolLifecycleError",
    "ProtocolRun",
    "ProtocolRunError",
    "ProtocolState",
    "ProtocolValidationError",
    "Ranking",
    "RankingStatus",
    "RecoveryCase",
    "RecoveryFailure",
    "RecoveryGate",
    "RecoveryKind",
    "RecoveryReplicate",
    "RecoverySpec",
    "ReportingSpec",
    "ScoreMetric",
    "ScoreSummary",
    "SelectionTieBreak",
    "Setting",
    "SourceSpec",
    "StudyProtocol",
    "TransformSpec",
    "TransformVisibility",
    "UnitRole",
    "UnitScore",
    "UnitSpec",
    "ValidationGeometry",
    "ValidationSpec",
    "WinnerPolicy",
    "compile_execution_plan",
    "fold_to_dict",
    "materialize_protocol",
    "protocol_from_dict",
    "protocol_from_json",
    "run_exact_recovery",
    "run_nested_protocol",
    "run_protocol",
    "validate_observation_contract",
    "verify_candidate_declarations",
]
